AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ClusterName:
    Type: String
    Default: default
  FunctionName:
    Type: String
    Default: defaultFunc

Transform: AWS::Serverless-2016-10-31
Description: Example
Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: main
      CodeUri: ./func.d
      Runtime: provided
      Layers:
        - !Sub "arn:aws:lambda:ap-northeast-1:${AWS::AccountId}:layer:layer-eks-kubectl-layer-stack:2"
      MemorySize: 512
      Environment:
        Variables:
          cluster_name: !Ref ClusterName
          iam_role_arn: arn:aws:iam::903779448426:role/eksdemo-NG-1RPL723W45VT5-NodeInstanceRole-1D4S7IF32IDU1
          aws_account_id: !Sub "${AWS::AccountId}"
          lambda_role_arn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaEKSAdminRole"
      # Policies: 
      #   - AWSLambdaBasicExecutionRole
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaEKSAdminRole"
      Timeout: 10

  UpdateCM:
    Type: Custom::UpdateConfigMap
    Properties:
      ServiceToken: !GetAtt Func.Arn
      NodeInstanceRole: xxxxxxxxxxxxxxx


Outputs:
  LambdaFuncArn:
    Description: Lambda Func ARN
    Value: !GetAtt Func.Arn
    Export:
      Name: !Sub 'LambdaFuncArn-${AWS::StackName}'
  LambdaFuncName:
    Description: Lambda Func Name
    Value: !Ref Func
    Export:
      Name: !Sub 'LambdaFuncName-${AWS::StackName}'
  LambdaRoleArn:
    Description: Lambda Role ARN
    Value: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaEKSAdminRole"
    Export:
      Name: !Sub 'LambdaRoleArn-${AWS::StackName}'
  # ResultData:
  #   Description: response of the custom resource
  #   Value: !GetAtt UpdateCM.Result
      
      