AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::ServerlessRepo::Application:
    Name: eks-auth-update-hook
    Description: "This Lambda function update the Amazon EKS aws-auth ConfigMap for you."
    Author: Pahud Hsieh
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['eks','aws-auth','ConfigMap','hook']
    HomePageUrl: https://github.com/pahud/lambda-layer-kubectl/tree/master/samples/update-configmap
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/pahud/lambda-layer-kubectl/tree/master/samples/update-configmap
    
Parameters:
  ClusterName:
    Type: String
    Default: default
  FunctionName:
    Type: String
    Default: defaultFunc
  NodeInstanceRoleArn:
    Type: String
  LambdaRoleArn:
    Type: String
  LambdaLayerKubectlArn:
    Type: String
    # Default: arn:aws:lambda:ap-northeast-1:${AWS::AccountId}:layer:layer-eks-kubectl-layer-stack:2
    

Transform: AWS::Serverless-2016-10-31
Description: Amazon EKS ConfigMap update handler
Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: main
      CodeUri: ./func.d
      Runtime: provided
      Layers:
        - !Ref LambdaLayerKubectlArn
        # - !Sub "arn:aws:lambda:ap-northeast-1:${AWS::AccountId}:layer:layer-eks-kubectl-layer-stack:2"
      MemorySize: 512
      Environment:
        Variables:
          cluster_name: !Ref ClusterName
          iam_role_arn: !Ref NodeInstanceRoleArn
          aws_account_id: !Sub "${AWS::AccountId}"
          lambda_role_arn: !Ref LambdaRoleArn
      # Policies: 
      #   - AWSLambdaBasicExecutionRole
      # Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaEKSAdminRole"
      Role: !Ref LambdaRoleArn
      Timeout: 10

  # UpdateCM:
  #   Type: Custom::UpdateConfigMap
  #   Properties:
  #     ServiceToken: !GetAtt Func.Arn


Outputs:
  LambdaFuncArn:
    Description: Lambda Func ARN
    Value: !GetAtt Func.Arn
  LambdaFuncName:
    Description: Lambda Func Name
    Value: !Ref Func
  LambdaRoleArn:
    Description: Lambda Role ARN
    Value: !Ref LambdaRoleArn
    # Value: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaEKSAdminRole"
  # ResultData:
  #   Description: response of the custom resource
  #   Value: !GetAtt UpdateCM.Result
      
      
